### ISSUE TITLE
Removing Guess bug

### ISSUE THREAD

**Issue by Evanstanislas** [ybenhayun/wordlebot#14]
Removing guess only works on 1 of the interface, making removing guess for the multiple wordle (dordle, quordle etc.) impossible.

This is the example on Quordle
<img width="393" alt="image" src="https://github.com/ybenhayun/wordlebot/assets/115131773/637439ee-58ac-4431-a5a1-148187c9dfa6">

**Comment by ybenhayun** [comment]
Thanks for catching this-- not sure where this bug came in but it should be fixed now.
