### ISSUE TITLE
Antiwordle Bot bug?

### ISSUE THREAD

**Issue by tamhar** [ybenhayun/wordlebot#2]
When using antiwordle, it seems there is a bug because after initial entry (usually QAJAQ), there is nothing happen when I click "calculate next guess". The other bot is fine, only antiwordle.

**Comment by ybenhayun** [comment]
Huh-- looks like you're right. It seems like this is just on normal mode. I have an idea what the bug might be (something similar happened with xordle) so I'll check it out soon. Thanks for the heads up!
